# RenciMobChaos by RenciDev
spawn-chance: 50 # Spawn chance: from 0% to 100%
radius: 4 # Spawn radius
mobs:
  - zombie
  - skeleton
  - creeper
  - chicken
  - pig
messages: # compatible minimessage
  mob-spawn: "<gradient:#74FF94:#B4EDFF>Explosion!</gradient> <red>Came out of the ground <bold><color:#ff5555><mob></color></bold>!</red>"